INSERT INTO department
VALUES  ("Screening"),
        ("Receiving"),
        ("Data Review"),
        ("Confirmations Aliquoting"),
        ("GC/MS"),
        ("QC");

INSERT INTO role
VALUES  ("Supervisor", 70000, 1),
        ("Supervisor", 50000, 2),
        ("Supervisor", 90000, 3),
        ("Supervisor", 50000, 4),
        ("Supervisor", 80000, 5),
        ("Supervisor", 60000, 6),
        ("Accessioner", 35000, 2),
        ("Technologist", 50000, 1),
        ("QC Analyst", 50000, 6), 
        ("Technologist", 55000, 5),
        ("Certifying Scientist", 65000, 3),
        ("Technician", 40000, 4),
        ("Technician", 40000, 1),
        ("Team Lead", 60000, 1),
        ("Team Lead", 45000, 2),
        ("Team Lead", 45000, 4),
        ("Team Lead", 65000, 5),
        ("Team Lead", 55000, 6);

INSERT INTO employee
VALUES  ("Scott", "DeVries", 14, 2),
        ("Amos", "McKenzie", 1, NULL), 
        ("Charles", "Hanna", 4, NULL), 
        ("Sandro", "Rojas", 8, 2), 
        ("Cory", "Bell", 5, NULL), 
        ("Michael", "Hodges", 13, 2),
        ("Korie", "Huggins", 11, 8),
        ("Odebowale", "Ojutiku", 5, NULL),
        ("Julian", "Bartkiewicz", 8, 2),
        ("Kimberly", "Jones", 8, 2), 
        ("Devonda", "McGowan", 8, 2),
        ("Michael", "Slade", 8, 2),
        ("Ben", "Holderby", 14, 2),
        ("Flossie", "Sowe", 11, 8),
        ("Tina", "Doles", 5, NULL), 
        ("Tammi", "Shirey", 11, 8), 
        ("Val", "Mack", 11, 15),
        ("Debbie", "McLean", 6, NULL), 
        ("Steve", "Henson", 6, 18),
        ("Beverly", "Pressly", 9, 18),
        ("Vivekananda", "Murthy", 5, NULL),
        ("Kim", "Carrington", 2, 23), 
        ("Gloria", "Gamble", 2, NULL),
        ("Rahim", "Uddin", 7, 24),
        ("Anita", "Snow", 15, 24),
        ("Deborah", "Snype", 7, 23);